const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'pro.js'),'utf8');
const context={window:{},document:{baseURI:'https://example.test/Journaling_trade.github.io/'},URL,URLSearchParams,AbortController,AbortSignal,DOMException,Blob,Date,Intl,setTimeout,clearTimeout,crypto:require('node:crypto').webcrypto};
let owner='user-a',token='valid-token',response={plan:'pro',effective_until:new Date(Date.now()+3600000).toISOString(),ai:{remaining:30,limit:30}},calls=[],status=200,onFetch;
context.fetch=async(url,options)=>{calls.push({url,options});if(onFetch)await onFetch();return {status,ok:status<400,json:async()=>response};};
vm.runInNewContext(source,context);const api=context.window.JTPRO;
const setup=(extra={})=>api.configure({apiBase:'https://gateway.test',getToken:async()=>token,getUserId:()=>owner,...extra});
(async()=>{
  assert.equal(Object.keys(api.features).length,10);
  assert.equal(api.safeLink('javascript:alert(1)'),null);
  assert.equal(api.safeLink('https://user:password@example.test/a'),null);
  assert.equal(api.safeLink('http://example.test/a'),null);
  assert.equal(api.safeLink('https://publisher.test/article'),'https://publisher.test/article');
  setup();assert.equal((await api.verifyAccess()).plan,'pro');
  assert.equal(calls[0].url,'https://gateway.test/api/v1/entitlements');assert.equal(calls[0].options.headers.Authorization,'Bearer valid-token');assert.equal(calls[0].options.credentials,'omit');
  setup({apiBase:'https://gateway.test/api/v1/'});await api.request('/usage');assert.equal(calls.at(-1).url,'https://gateway.test/api/v1/usage');
  const file=new Blob(['trade,pnl\nEURUSD,10'],{type:'text/csv'});await api.request('/imports/files',{method:'POST',body:file,rawBody:true,contentType:'text/csv',headers:{Authorization:'Bearer attacker'}});assert.equal(calls.at(-1).options.body,file);assert.equal(calls.at(-1).options.headers.Authorization,'Bearer valid-token');assert.equal(calls.at(-1).options.headers['Content-Type'],'text/csv');
  await assert.rejects(()=>api.request('/imports/files',{method:'POST',body:'unsafe',rawBody:true,contentType:'text/csv'}),/Invalid import/);
  for(const url of ['', 'http://public.test','https://secret@public.test','https://public.test?secret=1']) {setup({apiBase:url});await assert.rejects(()=>api.request('/usage'));}
  setup({apiBase:'http://127.0.0.1:8000'});await api.request('/usage');
  setup();await assert.rejects(()=>api.request('/../admin'));await assert.rejects(()=>api.open('unknown'));
  response={plan:'pro',effective_until:new Date(Date.now()-1000).toISOString()};await assert.rejects(()=>api.verifyAccess(),/expired/);assert.equal(api.access,null);
  response={plan:'pro'};await assert.rejects(()=>api.verifyAccess(),/expired/);
  response={plan:'admin'};await assert.rejects(()=>api.verifyAccess(),/Invalid entitlement/);
  response={plan:'free'};assert.equal((await api.verifyAccess()).plan,'free');
  response={plan:'plus'};assert.equal((await api.verifyAccess()).plan,'plus');
  onFetch=async()=>{owner='user-b';};await assert.rejects(()=>api.request('/accounts'),error=>error.name==='AbortError');owner='user-a';onFetch=null;
  let releaseOld;const oldResponse=new Promise(resolve=>releaseOld=resolve);
  response={items:[]};onFetch=()=>oldResponse;
  const oldRead=api.request('/news?country=US',{latest:true});
  await new Promise(resolve=>setImmediate(resolve));onFetch=null;
  await api.request('/news?country=GB',{latest:true});releaseOld();
  await assert.rejects(oldRead,error=>error.name==='AbortError','A late response overwrote the newer filter selection');
  let cleared=0;setup({onAccessChange:value=>{if(value===null)cleared++;}});status=403;response={detail:'Pro required'};await assert.rejects(()=>api.request('/analytics/overview'),/Pro required/);assert.ok(cleared>0);assert.equal(api.access,null);
  status=200;response=null;await assert.rejects(()=>api.request('/accounts'),/invalid response/);
  token='';await assert.rejects(()=>api.request('/accounts'),/Sign in/);token='valid-token';owner=null;await assert.rejects(()=>api.request('/accounts'),/Sign in/);owner='user-a';
  const points=[{date:'2026-01-01',equity:'100',drawdown:'0'},{date:'2026-01-02',equity:'98',drawdown:'2'},{date:'2026-02-02',equity:'110',drawdown:'0'}];
  assert.equal(api.aggregateSeries(points,'day').length,3);assert.equal(api.aggregateSeries(points,'month').length,2);assert.equal(api.aggregateSeries(points,'month')[0].equity,'98');assert.equal(api.aggregateSeries(points,'week')[0].date,'2025-12-29');
  assert.ok(!source.includes('innerHTML'));assert.ok(!source.includes('localStorage'));assert.ok(source.includes("'Idempotency-Key':crypto.randomUUID()"));
  setup({requestTimeout:10,getToken:()=>new Promise(()=>{})});
  const keepAlive=setTimeout(()=>{},100);await assert.rejects(()=>api.request('/entitlements'),error=>error.name==='TimeoutError');clearTimeout(keepAlive);
  api.reset();assert.equal(api.access,null);console.log('Pro frontend entitlement, owner isolation, API validation and chart aggregation checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
